<?php
/* === Developer Notes ======================================================== *
 * Copyright (c) 2017-2018 Mootly Obviate - See /LICENSE.md
 * --- Revision History ------------------------------------------------------- *
 * 2018-05-09 | Copied over from test page.
 * ---------------------------------------------------------------------------- */
                    # Call config to init the application
require_once( $_SERVER['DOCUMENT_ROOT'].'/config.php' );
                    # Build the page ------------------------------------------ *
                    # Content developers shouldn't touch anything above here.
                    # ↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓ EDIT BELOW ↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓
                    # page_name should equal your H1 title.
$mpo_parts->h1_title          = 'Constants';
$mpo_parts->link_title        = 'Constants';
$mpo_parts->page_name         = $mpo_parts->h1_title;
$mpo_parts->section_name      = 'Documentation: CMS Developer Notes';
// $mpo_parts->section_base      = $mpo_parts->site_base .'/docs'
$mpo_parts->section_base      = $mpo_paths->docs;
$mpo_parts->accessibility     = 'standard';
$mpo_parts->pagemenu          = 'perm';
$mpo_parts->bodyclasses       = 'final';
                    # import page components that are not generated by template.
require_once( $mpo_paths->php_widgets.'/menus/simple_crumbs.php' );
                    # The main content body of the page is developed here.
                    # It can be built from pieces or written as a block,
                    # depending on the site.
ob_start();
?>
<!-- *** BEGIN CONTENT ******************************************************** -->
<p>This is a list of the contants that are defined in the CMS.</p>

<dl class="inline-terms">
  <dt id="dfn-currpath"><code>CURR_PATH</code></dt>
  <dd>
    <p>The current path as taken from <code> dirname($_SERVER['SCRIPT_NAME'])</code>.</p>
  </dd>
  <dt id="dfn-defclasslib"><code>DEF_CLASSLIB</code></dt>
  <dd>
    <p>The path to the template class library for back-end processing.</p>
  </dd>
  <dt id="dfn-defhome"><code>DEF_HOME</code></dt>
  <dd>
    <p>If the home page for this site is someplace other than root, this specifies the correct directory path.</p>
  </dd>
  <dt id="dfn-defprefix"><code>DEF_PREFIX</code></dt>
  <dd>
    <p>The template prefix that defines the template family or client name.</p>
  </dd>
  <dt id="dfn-defroot"><code>DEF_ROOT</code></dt>
  <dd>
    <p>The root of the site for templating processes. By default, this is an empty string.</p>
  </dd>
  <dt id="dfn-deftemplate"><code>DEF_TEMPLATE</code></dt>
  <dd>
    <p>The template name. This is prefixed by the <code>DEF_PREFIX</code> to define the template path: <code><var>prefix</var>_<var>name</var></code>.</p>
  </dd>
  <dt id="dfn-mpclasslib"><code>MP_CLASSLIB</code></dt>
  <dd>
    <p>The path to the main class library for back-end processing.</p>
  </dd>
  <dt id="dfn-mppsep"><code>MP_PSEP</code></dt>
  <dd>
    <p>The path separator ro use in building paths. The default is <code>/</code>.</p>
  </dd>
  <dt id="dfn-mproot"><code>MP_ROOT</code></dt>
  <dd>
    <p>The site root for back-end processes. Takes the value of <code>$_SERVER['DOCUMENT_ROOT']</code>.</p>
    <p>There should be no reason to change this value.</p>
  </dd>
  <dt id="dfn-permtemplate"><code>PERM_TEMPLATE</code></dt>
  <dd>
    <p>The fallback template in case there are template issues. The default is <code>mp_basic</code>. This does not gurantee pages using different templates will work with the fall back.</p>
  </dd>
</dl>

<!-- *** end contents ********************************************************* -->
<?php
                    # ↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑ EDIT ABOVE ↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑
                    # Content developers shouldn't touch anything below here.
$mpo_parts->main_content = ob_get_clean();
ob_end_clean();
                    // Submit to template generator --------------------------- *
mpf_renderPage($mpo_parts->template.$mpt_['default'].$mpt_['suffix'], $mpo_parts);
?>
