<?php
/* === Developer Notes - Twig Template Widgets ================================ *
 * Copyright (c) 2020 Mootly Obviate - See /LICENSE.md
 * --- Revision History ------------------------------------------------------- *
 * 2020-02-01 | Add page.
 * ---------------------------------------------------------------------------- */
                    # Call config to init the application
require_once( $_SERVER['DOCUMENT_ROOT'].'/config.php' );
                    # Build the page ------------------------------------------ *
                    # Content developers shouldn't touch anything above here.
                    # ↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓ EDIT BELOW ↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓
                    # page_name should equal your H1 title.
$mpo_parts->h1_title          = 'Twig Widgets';
$mpo_parts->link_title        = 'Twig Widgets';
$mpo_parts->page_name         = $mpo_parts->h1_title;
$mpo_parts->section_name      = 'Docs : CMS Dev Notes';
$mpo_parts->section_base      = $mpo_paths->docs;
$mpo_parts->bodyclasses       = 'final tech-notes';
$mpo_parts->pagemenu          = 'import';
                    # import page components that are not generated by template.
require_once( MP_ROOT.'/docs/_assets/includes/menu.docs.php' );
require_once( $mpo_paths->php_widgets.'/menus/simple_crumbs.php' );
                    # The main content body of the page is developed here.
                    # It can be built from pieces or written as a block,
                    # depending on the site.
ob_start();
?>
<!-- *** BEGIN CONTENT ******************************************************** -->

<h2>A List of Twig Template Widgets</h2>

<div class="note">
  <p><span class="title">Note:</span> This page refers to a new version of the default template currently in development.</p>
</div>

<p>This is a list of <a href="https://twig.symfony.com/" target="_blank">Twig</a> widgets in the base template that are available to you in the base template. They are in aphabetical order by topic.</p>

<p>All these widgets are contained in a division with a class of <code>widget</code>. Most also have a unique ID.</p>

<p>These widgets are in <code><var>{template path}</var>/_assets/includes/widgets/</code>.</p>

<dl class="clamshell">
  <dt>Copyright, site code</dt>
  <dd>
    <p>This is a notice that indicates the copyright information for the site and the underlying codebase for the site. Including it is optional. If you are using the MoosePlum CMS base, please leave the Mootly Obviate attribution and add you own name before it with a comma.</p>
    <p><span class="leadin-title">File name:</span> <code>copyright-site.html.twig</code>.</p>
    <p><span class="leadin-title">Container ID:</span> <code>mp_copyright-site</code></p>
  </dd>
  <dt>Copyright, template</dt>
  <dd>
    <p>This is a notice that normally appears in the footer of each page indicates the copyright information for the site and the underlying code, but not necessarily the content on the individual pages. Remember to change it when publishing you own site unless you want to assign owndership of all your awesome template designs to me.</p>
    <p><span class="leadin-title">File name:</span> <code>copyright-template.html.twig</code>.</p>
    <p><span class="leadin-title">Container ID:</span> <code>mp_copyright-template</code></p>
  </dd>
</dl>

<!-- *** end contents ********************************************************* -->
<?php
                    # ↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑ EDIT ABOVE ↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑
                    # Content developers shouldn't touch anything below here.
$mpo_parts->main_content = ob_get_clean();
ob_end_clean();
                    // Submit to template generator --------------------------- *
mpf_renderPage($mpo_parts->template.$mpt_['default'].$mpt_['suffix'], $mpo_parts);
?>
