<?php
/* === Style Guide: Headings ================================================== *
 * Copyright (c) 2017-2018 Mootly Obviate - See /LICENSE.md
 * --- Revision History ------------------------------------------------------- *
 * 2018-05-09 | Copied over from test page.
 * ---------------------------------------------------------------------------- */
                    # Call config to init the application
require_once( $_SERVER['DOCUMENT_ROOT'].'/config.php' );
                    # Build the page ------------------------------------------ *
                    # Content developers shouldn't touch anything above here.
                    # ↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓ EDIT BELOW ↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓
                    # page_name should equal your H1 title.
$mpo_parts->h1_title          = 'Template Colors';
$mpo_parts->link_title        = 'Template Colors';
$mpo_parts->page_name         = $mpo_parts->h1_title;
$mpo_parts->section_name      = 'Documentation: Style Guide';
$mpo_parts->section_base      = '/docs';
$mpo_parts->accessibility     = 'standard';
$mpo_parts->pagemenu          = 'perm';
$mpo_parts->bodyclasses       = 'final';
$page_path                    = $mpo_parts->page_path;
                    # import page components that are not generated by template.
require_once( $mpo_paths->php_widgets.'/menus/simple_crumbs.php' );
                    # The main content body of the page is developed here.
                    # It can be built from pieces or written as a block,
                    # depending on the site.
ob_start();
?>
<!-- *** BEGIN CONTENT ******************************************************** -->

<p>The last column contains the variables as called in the CSS as well as sample swatches for color blends.
<h2 id="toc-links">Contents</h2>

<!-- *** PURPLES *** ********************************************************** -->
<h2>Purples</h2>

<table class="list-table" title="Color swatches of template purples">
  <thead>
    <tr>
      <th scope="col">Swatch</th>
      <th scope="col">RGB</th>
      <th scope="col">Hex</th>
      <th scope="col">Name</th>
      <th scope="col">Called Variables</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th style="background-color: rgb(67,40,93);"> </th>
      <td>rgb(67,40,93)</td>
      <td>#43285d</td>
      <td>$c-purple-web-1</td>
      <td>
        <ul>
          <li>$c-banner-bg</li>
          <li>$c-button-bg</li>
          <li style="color:#fcf8fb; background-color:#294E7D;">$c-visited-text <br />mix($c-core-links, $c-purple-web-1, 50)</li>
        </ul>
      </td>
    </tr>
  </tbody>
</table>

<!-- *** end contents ********************************************************* -->
<?php
$mpo_parts->main_content = ob_get_clean();
ob_end_clean();
$page_elements = $mpo_parts->build_page();
echo ($twig->render($mpo_parts->template.$mpt_full_template, array('page'=>$page_elements['content'])));
?>
