&lt;<?php
/* === Style Guide: Tables ==================================================== *
 * Copyright (c) 2017-2018 Mootly Obviate - See /LICENSE.md
 * --- Revision History ------------------------------------------------------- *
 * 2018-05-09 | Copied over from test page.
 * ---------------------------------------------------------------------------- */
                    # Call config to init the application
require_once( $_SERVER['DOCUMENT_ROOT'].'/config.php' );
                    # Build the page ------------------------------------------ *
                    # Content developers shouldn't touch anything above here.
                    # ↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓ EDIT BELOW ↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓
                    # page_name should equal your H1 title.
$mpo_parts->h1_title          = 'Forms';
$mpo_parts->link_title        = 'Forms';
$mpo_parts->page_name         = $mpo_parts->h1_title;
$mpo_parts->section_name      = 'Documentation: Forms';
$mpo_parts->section_base      = '/docs';
$mpo_parts->accessibility     = 'standard';
$mpo_parts->pagemenu          = 'perm';
$mpo_parts->bodyclasses       = 'final';
$page_path                    = $mpo_parts->page_path;
                    # import page components that are not generated by template.
require_once( $mpo_paths->php_widgets.'/menus/simple_crumbs.php' );
                    # The main content body of the page is developed here.
                    # It can be built from pieces or written as a block,
                    # depending on the site.
ob_start();
?>
<!-- *** BEGIN CONTENT ******************************************************** -->
<h2 id="toc-links">Contents</h2>

<form method="post" action="#" name="examples" id="form_examples">
</form>

<h2>Fieldsets</h2>

<fieldset form="form_examples" name="fs_example" id="form_fs_example">
  <legend>Legend Text</legend>
  <div class="form_directions directions">
    <p>Directions for the fieldset.</p>
  </div>
  <div class="field_container">
    <p>
      <label for="form_xmp01">Label</label>
      <input form="form_examples" type="text" name="xmp01" id="form_xmp01" value="" size="30" />
    </p>
  </div>
</fieldset>

<fieldset form="form_examples" name="fs_example" id="form_fs_example">
  <legend class="subLegend">Subsidiary Fieldset</legend>
  <div class="form_directions directions">
    <p>This fieldset should be perceived as a child of the previous element.</p>
  </div>
  <div class="field_container">
    <p>
      <label for="form_xmp02">Label</label>
      <input form="form_examples" type="text" name="xmp02" id="form_xmp02" value="" size="30" />
    </p>
  </div>
</fieldset>

<div id="div_reviewSubs" class="fieldset">
  <h3 class="legend">Division Emulation Fieldset (.fieldset)</h3>
  <div class="set_content">
    <p>This is just a division styled to match the fieldselt Useful for long sets of directions, results boxes for interactive forms, etc.</p>
  </div>
</div>

<h2>Text Fields</h2>

<p>Default labels are 8ems on the left. Expected code is as follows.</p>

<pre>
&lt;fieldset form="" name="" id=""&gt;
  &lt;legend&gt;Legend&lt;/legend&gt;
  &lt;div class="field_container"&gt;
    &lt;p&gt;
      &lt;label for="f"&gt;Text&lt;/label&gt;
      &lt;input form="" type="" name="" id="" value="" size="" placeholder="" /&gt;
    &lt;/p&gt;
    &vellip;
  &lt;/div&gt;
&lt;/fieldset&gt;
</pre>
<fieldset form="form_examples" name="fs_rxtfields" id="form_fs_textfields">
  <legend>Legend</legend>
  <div class="field_container">
    <p>
      <label for="form_text01">Text</label>
      <input form="form_examples" type="text" name="text01" id="form_text1" value="" size="30" placeholder="text field" />
    </p>
    <p>
      <label for="form_pass01">Password</label>
      <input form="form_examples" type="password" name="pass01" id="form_pass01" value="" size="30" placeholder="password" />
    </p>
    <p>
      <label for="form_date01">Date</label>
      <input form="form_examples" type="date" name="date01" id="form_date01" value="" size="30" placeholder="date" />
    </p>
    <p>
      <label for="form_time01">Time</label>
      <input form="form_examples" type="time" name="time01" id="form_time01" value="" size="30" placeholder="time" />
    </p>
    <p>
      <label for="form_email01">Email</label>
      <input form="form_examples" type="email" name="email01" id="form_email01" value="" size="30" placeholder="email" />
    </p>
    <p>
      <label for="form_tel01">Telephone</label>
      <input form="form_examples" type="tel" name="tel01" id="form_tel01" value="" size="30" placeholder="telephone" />
    </p>
  </div>
</fieldset>
<!-- *** end contents ********************************************************* -->
<?php
                    # ↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑ EDIT ABOVE ↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑
                    # Content developers shouldn't touch anything below here.
                    # Invoke the template ------------------------------------- *
$mpo_parts->main_content = ob_get_clean();
ob_end_clean();
$page_elements = $mpo_parts->build_page();
echo ($twig->render($mpo_parts->template.$mpt_full_template, array('page'=>$page_elements['content'])));
?>
