<?php
/* === Style Guide: Forms ==================================================== *
 * Copyright (c) 2017-2020 Mootly Obviate - See /LICENSE.md
 * --- Revision History ------------------------------------------------------- *
 * 2018-05-09 | Copied over from test page.
 * ---------------------------------------------------------------------------- */
                    # Call config to init the application
require_once( $_SERVER['DOCUMENT_ROOT'].'/config.php' );
                    # Build the page ------------------------------------------ *
                    # Content developers shouldn't touch anything above here.
                    # ↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓ EDIT BELOW ↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓
                    # page_name should equal your H1 title.
$mpo_parts->h1_title          = 'Forms';
$mpo_parts->link_title        = 'Forms';
$mpo_parts->page_name         = $mpo_parts->h1_title;
$mpo_parts->section_name      = 'Docs : Forms';
$mpo_parts->section_base      = $mpo_paths->docs;
$mpo_parts->pagemenu          = 'import';
$mpo_parts->bodyclasses       = 'final';
                    # import page components that are not generated by template.
ob_start();
require_once( MP_ROOT.'/docs/_assets/includes/menu.docs.php' );
$mpo_parts->page_menu = ob_get_clean();
ob_end_clean();
require_once( $mpo_paths->php_widgets.'/menus/simple_crumbs.php' );
                    # The main content body of the page is developed here.
                    # It can be built from pieces or written as a block,
                    # depending on the site.
ob_start();
?>
<!-- *** BEGIN CONTENT ******************************************************** -->
<h2 id="toc-links">Contents</h2>

<form method="post" action="#" name="form_examples" id="form_examples">

<h2>Fieldsets</h2>

<fieldset form="form_examples" name="fs_example" id="field_fs_example">
  <legend>Fieldset Examples</legend>
  <div class="field_directions directions">
    <p>Directions for the fieldset.</p>
  </div>
  <div class="field_container">
    <p>
      <label for="field_xmp01">Label</label>
      <input form="form_examples" type="text" name="xmp01" id="field_xmp01" value="" size="30" />
    </p>
  </div>
</fieldset>

<fieldset form="form_examples" name="fs_subexample" id="field_fs_subexample">
  <legend class="subLegend">Subsidiary Fieldset</legend>
  <div class="field_directions directions">
    <p>This fieldset should be perceived as a child of the previous element.</p>
  </div>
  <div class="field_container">
    <p>
      <label for="field_xmp02">Label</label>
      <input form="form_examples" type="text" name="xmp02" id="field_xmp02" value="" size="30" />
    </p>
  </div>
</fieldset>

<div id="div_reviewSubs" class="fieldset">
  <h3 class="legend">Division Emulation Fieldset (.fieldset)</h3>
  <div class="set_content">
    <p>This is just a division styled to match the fieldselt Useful for long sets of directions, results boxes for interactive forms, etc.</p>
  </div>
</div>

<h2>Text Fields</h2>

<p>Default labels are 8ems on the left. Expected code is as follows.</p>

<pre>
&lt;fieldset form="" name="" id=""&gt;
  &lt;legend&gt;Legend&lt;/legend&gt;
  &lt;div class="field_container"&gt;
    &lt;p&gt;
      &lt;label for="f"&gt;Text&lt;/label&gt;
      &lt;input form="" type="" name="" id="" value="" size="" placeholder="" /&gt;
    &lt;/p&gt;
    &vellip;
  &lt;/div&gt;
&lt;/fieldset&gt;
</pre>
<fieldset form="form_examples" name="fs_textfields" id="field_fs_textfields">
  <legend>Text Field Examples</legend>
  <div class="field_container">
    <p>
      <label for="field_text01">Text</label>
      <input form="form_examples" type="text" name="text01" id="field_text01" value="" size="30" placeholder="text field" />
    </p>
    <p>
      <label for="field_pass01">Password</label>
      <input form="form_examples" type="password" name="pass01" id="field_pass01" value="" size="30" placeholder="password" />
    </p>
    <p>
      <label for="field_date01">Date</label>
      <input form="form_examples" type="date" name="date01" id="field_date01" value="" size="30" placeholder="mm/dd/yyyy" />
    </p>
    <p>
      <label for="field_time01">Time</label>
      <input form="form_examples" type="time" name="time01" id="field_time01" value="" size="30" placeholder="hh:mm am/pm" />
    </p>
    <p>
      <label for="field_email01">Email</label>
      <input form="form_examples" type="email" name="email01" id="field_email01" value="" size="30" placeholder="email" />
    </p>
    <p>
      <label for="field_tel01">Telephone</label>
      <input form="form_examples" type="tel" name="tel01" id="field_tel01" value="" size="30" placeholder="telephone" />
    </p>
    <p class="fullWidth">
      <label for="field_textwide">Full width</label>
      <input form="form_examples" type="text" name="textwide" id="field_textwide" value="" size="30" placeholder="this field uses .fullWidth" />
    </p>
    <p>
      <label for="field_small01">Small field</label>
      <input form="form_examples" type="text" name="smallt01" id="field_small01" value="" size="2" placeholder="" class="twochar" />
    </p>
  </div>
  <div class="center">
    <p><label for="field_longtext">Text area example</label></p>
    <textarea form="form_examples" name="longext" id="field_longtext" placeholder="Ex officia officia cupidatat consectetur adipisicing veniam voluptate veniam nostrud aliquip. Aliqua labore fugiat do proident adipisicing nulla commodo occaecat laboris nisi. Consectetur officia ullamco veniam excepteur tempor aliquip tempor."></textarea>
  </div>
</fieldset>

<h2>Highlighted Text Fields</h2>

<fieldset form="form_examples" name="fs_hitext" id="field_fs_hitext">
  <legend>Highlighted Text Field Examples</legend>
  <div class="field_container">
    <p>
      <label for="field_hitext01">Has focus</label>
      <input form="form_examples" type="text" name="hitext01" id="field_hitext01" value="" size="30" placeholder="has focus" class="xmp_fieldfocus" />
    </p>
    <p>
      <label for="field_hitext02">Is invalid</label>
      <input form="form_examples" type="text" name="hitext02" id="field_hitext02" value="" size="30" placeholder="is invalid" class="xmp_fieldinvalid" />
    </p>
    <p>
      <label for="field_datefocus">Date has focus</label>
      <input form="form_examples" type="date" name="datefocus" id="field_datefocus" value="" size="30" placeholder="mm/dd/yyyy" class="xmp_fieldfocus" />
    </p>
    <p>
      <label for="field_dateinvalid">Date is invalid</label>
      <input form="form_examples" type="date" name="dateinvalid" id="field_dateinvalid" value="" size="30" placeholder="mm/dd/yyyy" class="xmp_fieldinvalid" />
    </p>
  </div>
</fieldset>

<h2>Select Fields</h2>

<fieldset form="form_examples" name="fs_selfields" id="field_fs_selfields">
  <legend>Selection Field Exampels</legend>
  <div class="field_directions">
    <p>The first field is an example of a select field locked to a text field. Each updates the other.</p>
  </div>
  <div class="field_container">
    <p>
      <label for="field_subsLang">Lang code</label>
      <input form="form_examples" class="matchedText twochar" type="text" name="subsLang" id="field_subsLang" value="" size="2" />
      <label for="field_subsLangSel" class='reader-only'>Lang code list</label>
      <select form="form_examples" class="matchedSel" name="subsLangSel" id="field_subsLangSel">
        <option value="invalid">Select</option>
        <option value="CH">Chinese</option>
        <option value="CR">Creole</option>
        <option value="EN">English</option>
        <option value="FR">French</option>
        <option value="GR">German</option>
        <option value="HI">Hindi</option>
        <option value="HW">Hebrew</option>
        <option value="IT">Italian</option>
        <option value="JP">Japanese</option>
        <option value="KR">Korean</option>
        <option value="MU">Multiple</option>
        <option value="PL">Polish</option>
        <option value="RS">Russian</option>
        <option value="SI">Sign</option>
        <option value="SP">Spanish</option>
        <option value="VT">Vietnamese</option>
        <option value="XX">Other</option>
      </select>
    </p>
  </div>
  <div class="field_directions">
    <p>The following are checkboxes as selectable buttons.</p>
  </div>
  <div class="field_container">
    <p class="fullWidth">
      <input form="form_examples" type="checkbox" name="chsel_11" id="field_chsel_11" value="11" class="makeButton" />
      <label for="field_chsel_11"><span>Label 1</span></label>
      <input form="form_examples" type="checkbox" name="chsel_12" id="field_chsel_12" value="12" class="makeButton" />
      <label for="field_chsel_12"><span>Label 2</span></label>
      <input form="form_examples" type="checkbox" name="chsel_21" id="field_chsel_21" value="21" class="makeButton" />
      <label for="field_chsel_21"><span>Label 3</span></label>
      <input form="form_examples" type="checkbox" name="chsel_22" id="field_chsel_22" value="22" class="makeButton" />
      <label for="field_chsel_22"><span>Label 4</span></label>
      <input form="form_examples" type="checkbox" name="chsel_31" id="field_chsel_31" value="31" class="makeButton" />
      <label for="field_chsel_31"><span>Label 5</span></label>
      <input form="form_examples" type="checkbox" name="chsel_32" id="field_chsel_32" value="32" class="makeButton suspList" />
      <label for="field_chsel_32"><span>Label 6</span></label>
    </p>
  </div>
  <div class="field_directions">
    <p>The following are radio buttons as selectable buttons.</p>
  </div>
  <div class="field_container">
    <p class="fullWidth">
      <input form="form_examples" type="radio" name="susr_11" id="field_susr_1" value="11" class="makeButton" />
      <label for="field_susr_1"><span>Label A</span></label>
      <input form="form_examples" type="radio" name="susr_11" id="field_susr_2" value="12" class="makeButton" />
      <label for="field_susr_2"><span>Label B</span></label>
      <input form="form_examples" type="radio" name="susr_11" id="field_susr_3" value="21" class="makeButton" />
      <label for="field_susr_3"><span>Label C</span></label>
    </p>
  </div>
  <div class="field_directions">
    <p>There is the option for a delete tab on dynamically generated selectors. Requires JS to add and remove the selectors.</p>
  </div>
  <div class="field_container">
    <p class="clickable_box">
      <input form="form_examples" type="radio" name="delbox" id="field_delbox" value="" class="makeButton" checked />
      <label for="field_delbox"><span>Selected item</span></label>
      <span class="bottom-tab-box"><a href="#" class="delete_btn">Delete</a></span>
    </p>
    <p class="clickable_box">
      <input form="form_examples" type="radio" name="delbox" id="field_delbox2" value="" class="makeButton" />
      <label for="field_delbox2"><span>Unselected item</span></label>
      <span class="bottom-tab-box"><a href="#" class="delete_btn">Delete</a></span>
    </p>
  </div>
</fieldset>

<h2>Buttons</h2>

<fieldset form="form_examples" name="fs_btnfields" id="field_fs_btnfields">
  <legend>Button Examples</legend>
  <div class="field_container">
    <p>
      <input form="form_examples" type="button" value="input type button" id="field_btn" />
    </p>
    <p>
      <button form="form_examples" type="button" value="button" id="field_button">button element</button>
    </p>
    <p class="clear-left">
      <input form="form_examples" type="submit" value="submit" id="field_submit" />
    </p>
    <p>
      <input form="form_examples" type="reset" value="reset" id="field_reset" />
    </p>

  </div>
</fieldset>
</form>

<!-- *** end contents ********************************************************* -->
<?php
                    # ↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑ EDIT ABOVE ↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑
                    # Content developers shouldn't touch anything below here.
$mpo_parts->main_content = ob_get_clean();
ob_end_clean();
                    // Submit to template generator --------------------------- *
mpf_renderPage($mpo_parts->template.$mpt_['default'].$mpt_['suffix'], $mpo_parts);
?>
