<?php
/* === Style Guide ============================================================ *
 * Copyright (c) 2017-2018 Mootly Obviate - See /LICENSE.md
 * --- Revision History ------------------------------------------------------- *
 * 2018-05-09 | Copied over from test page.
 * ---------------------------------------------------------------------------- */
                    # Call config to init the application
require_once( $_SERVER['DOCUMENT_ROOT'].'/config.php' );
                    # Build the page ------------------------------------------ *
                    # Content developers shouldn't touch anything above here.
                    # ↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓ EDIT BELOW ↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓
                    # page_name should equal your H1 title.
$mpo_parts->h1_title          = 'Contents';
$mpo_parts->link_title        = 'Style Guide';
$mpo_parts->page_name         = $mpo_parts->h1_title;
$mpo_parts->section_name      = 'Documentation: Style Guide';
$mpo_parts->section_base      = $mpo_paths->docs;
                    # import page components that are not generated by template.
require_once( $mpo_paths->php_widgets.'/menus/simple_crumbs.php' );
                    # The main content body of the page is developed here.
                    # It can be built from pieces or written as a block,
                    # depending on the site.
ob_start();
?>
<!-- *** begin content ******************************************************** -->
<h2>What's Here</h2>

<table class="list-table" title="List of section contents">
  <thead>
    <tr>
      <th scope="col">Page</th>
      <th scope="col">Description</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th colspan="2">Style Guide</th>
    </tr>
    <tr>
      <td><a href="<?=CURR_PATH?>/callouts.php">Text Elements &amp; Callouts</a></td>
      <td>Text, text styling, and callouts.</td>
    </tr>
    <tr>
      <td><a href="<?=CURR_PATH?>/colors.php">Colors</a></td>
      <td>This page should be customized for each template.</td>
    </tr>
    <tr>
      <td><a href="<?=CURR_PATH?>/headings.php">Headings</a></td>
      <td>Headings and section spacing</td>
    </tr>
    <tr>
      <td><a href="<?=CURR_PATH?>/links.php">Links &amp; Images</a></td>
      <td>Link, images, and other embedded content</td>
    </tr>
    <tr>
      <td><a href="<?=CURR_PATH?>/lists.php">Lists</a></td>
      <td>Lists.</td>
    </tr>
    <tr>
      <td><a href="<?=CURR_PATH?>/tables.php">Tables</a></td>
      <td>The different tables currently available.</td>
    </tr>
    <tr>
      <td><a href="<?=CURR_PATH?>/forms.php">Forms</a></td>
      <td>Layouts for non-custom form fields.</td>
    </tr>
  </tbody>
</table>
<!-- *** end contents ********************************************************* -->
<?php
                    # ↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑ EDIT ABOVE ↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑
                    # Content developers shouldn't touch anything below here.
$mpo_parts->main_content = ob_get_clean();
ob_end_clean();
                    // Submit to template generator --------------------------- *
mpf_renderPage($mpo_parts->template.$mpt_['default'].$mpt_['suffix'], $mpo_parts);
?>
