<?php
/**
  * Configuration script.
  *
  * Set system varaibles here.
  *
  * @copyright 2017 Mootly Obviate
  * @package   moosepress
  * --------------------------------------------------------------------------- *
  * --- Revision History ------------------------------------------------------ *
  * 2019-07-09 | Added revision log, cleaned code
  * --------------------------------------------------------------------------- */

  # Constants ----------------------------------------------------------------- *
  # Use constants for our base variables: easy to see, can't be overwritten.
                    # Don't touch this - autogenerated ------------------------ *
                    # Specify the full site root.
                    # Use for object library pathing, e.g. C:/Web/moosepress.
  if (!defined('MP_ROOT'))      { define( 'MP_ROOT', $_SERVER['DOCUMENT_ROOT'].'/' ); }
                    # Core file paths ----------------------------------------- *
                    # Define the site root as used by templates.
                    # For                                | Value should be
                    # ---------------------------------- | --------------------
                    # standard pathing                   | leave blank
                    # servers that expect server pathing | match MP_ROOT
                    # subdomains as subfolders           | adjust accordingly
  if (!defined('DEF_ROOT'))     { define( 'DEF_ROOT', '' ); }
                    # Don't touch this - autogenerated ------------------------ *
                    # Keep user provided URLs out of config!
  if (!defined('CURR_PATH'))    { define( 'CURR_PATH', dirname($_SERVER['SCRIPT_NAME']) ); }
                    # Specify path to home page ------------------------------- *
                    # Use minimum valid path.
  if (!defined('DEF_HOME'))     { define( 'DEF_HOME', '/' ); }
                    # Specify template name ----------------------------------- *
                    # Use the following format: {prefix}_{name}
  if (!defined('DEF_PREFIX'))   { define( 'DEF_PREFIX', 'mp' ); }
  if (!defined('DEF_TEMPLATE')) { define( 'DEF_TEMPLATE', 'stars' ); }
                    # Specify path to template class library ------------------ *
                    # Leave initial slash off, path will be prepended.
  if (!defined('DEF_CLASSLIB')) { define( 'DEF_CLASSLIB', '_templates/mp_basic/class_lib/' ); }

# Initialize the Site --------------------------------------------------------- *
  require_once( MP_ROOT.'_core/init.php' );

# Specify site-wide template variables ---------------------------------------- *
                    # Specify site name in fill and abbreviated form ---------- *
  $mpo_parts->site_name     = 'MoosePress';
  $mpo_parts->site_abbr     = '[mp]';
                    # Specify page title elements ----------------------------- *
                    # Names are properties of _path object defined in page.
                    # format as below: page name | section | site name
  $mpo_parts->title_struct  = ['page_name','section_name','site_name'];
  $mpo_parts->separator     = ' | ';
                    # Define template library --------------------------------- *
                    # This is the only place the filenames should appear.
  $mpt_template     = array(
    'suffix'        => '.html.twig',    # default twig suffix
                    # template partials
    'header'        => 'page_header',   # header include
    'footer'        => 'page_footer',   # footer include
                    # page templates
    'default'       => 'page_default',  # standard content page
    'home'          => 'home_default',  # home/splash pages
    'forms'         => 'form_default',  # forms
  );

# Invoke Twig ----------------------------------------------------------------- *
  require_once( MP_ROOT.'_core/prep.php' );

# end config ------------------------------------------------------------------ *
